# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ub558QpB10UxufLNSurHBV_vHdp0VgDq
"""

!pip install mesa matplotlib seaborn

!pip install mesa

import mesa
print(mesa.__version__)

!pip uninstall -y mesa
!pip install mesa==3.4.0

!pip install mesa==1.1.0

# =========================
# Imports
# =========================
from mesa import Agent, Model
from mesa.time import RandomActivation
from mesa.space import MultiGrid
from mesa.datacollection import DataCollector

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# =========================
# Gini coefficient
# =========================
def compute_gini(model):
    agent_wealths = [agent.wealth for agent in model.schedule.agents]
    x = sorted(agent_wealths)
    N = model.num_agents
    B = sum((i + 1) * xi for i, xi in enumerate(x)) / (N * sum(x))
    return 1 + (1 / N) - 2 * B

# =========================
# Agent definition
# =========================
class MoneyAgent(Agent):
    def __init__(self, unique_id, model):
        super().__init__(unique_id, model)
        self.wealth = 1

    def move(self):
        possible_steps = self.model.grid.get_neighborhood(
            self.pos, moore=True, include_center=False
        )
        new_position = self.random.choice(possible_steps)
        self.model.grid.move_agent(self, new_position)

    def give_money(self):
        cellmates = self.model.grid.get_cell_list_contents([self.pos])
        if len(cellmates) > 1:
            other = self.random.choice(cellmates)
            if other != self:
                other.wealth += 1
                self.wealth -= 1

    def step(self):
        self.move()
        if self.wealth > 0:
            self.give_money()

# =========================
# Model definition
# =========================
class MoneyModel(Model):
    def __init__(self, N, width, height):
        super().__init__()
        self.num_agents = N
        self.grid = MultiGrid(width, height, torus=True)
        self.schedule = RandomActivation(self)

        for i in range(N):
            a = MoneyAgent(i, self)
            self.schedule.add(a)
            x = self.random.randrange(width)
            y = self.random.randrange(height)
            self.grid.place_agent(a, (x, y))

        self.datacollector = DataCollector(
            model_reporters={"Gini": compute_gini},
            agent_reporters={"Wealth": "wealth"}
        )
        self.datacollector.collect(self)

    def step(self):
        self.schedule.step()
        self.datacollector.collect(self)

# =========================
# Run model
# =========================
model = MoneyModel(50, 10, 10)
for _ in range(20):
    model.step()

# =========================
# Wealth histogram
# =========================
agent_wealth = [agent.wealth for agent in model.schedule.agents]
plt.hist(agent_wealth, bins=range(max(agent_wealth)+2), edgecolor='black')
plt.xlabel("Wealth")
plt.ylabel("Number of Agents")
plt.title("Wealth Distribution After 20 Steps")
plt.show()

# =========================
# Heatmap of agents per cell
# =========================
agent_counts = np.zeros((model.grid.width, model.grid.height))
for cell_content, x, y in model.grid.coord_iter():
    agent_counts[x][y] = len(cell_content)

sns.heatmap(agent_counts, cmap="viridis", annot=True, cbar=False, square=True)
plt.title("Number of Agents per Cell")
plt.show()

# =========================
# Animation
# =========================
fig, ax = plt.subplots(figsize=(4, 4), dpi=100)
fig.subplots_adjust(bottom=0.2)

def plot_grid(model):
    ax.clear()
    ax.set_xticks(range(model.grid.width))
    ax.set_yticks(range(model.grid.height))
    for agent in model.schedule.agents:
        if agent.wealth > 0:
            ax.scatter(agent.pos[1], agent.pos[0], facecolors='none', edgecolors='red', s=200)
        else:
            ax.scatter(agent.pos[1], agent.pos[0], color='grey', s=100)
    ax.set_title(f"Money Model: Step {model.schedule.steps}", fontsize=16)
    ax.set_xlim(-1, model.grid.width)
    ax.set_ylim(-1, model.grid.height)

fig.text(0.1, 0.1, "Red: Wealth > 0", fontsize=8, color='red')
fig.text(0.1, 0.05, "Grey: Wealth = 0", fontsize=8, color='grey')

plot_grid(model)

def update(frame):
    if frame > 0:
        model.step()
    plot_grid(model)

anim = FuncAnimation(fig, update, frames=101, repeat=False, interval=200)
HTML(anim.to_jshtml())

# =========================
# Batch runner
# =========================
params = {
    "N": np.arange(10, 51, 10),
    "width": 10,
    "height": 10
}

param_run = mesa.batch_run(
    MoneyModel,
    parameters=params,
    iterations=1,
    max_steps=30,
    number_processes=1,
    data_collection_period=1,
    display_progress=True
)

batch_ID_results = pd.DataFrame(param_run)

plt.figure(figsize=(12, 6))
sns.lineplot(data=batch_ID_results, x="Step", y="Gini", hue="N", marker="o")
plt.title("Gini Coefficient Over Time for Different Agent Counts (N)")
plt.xlabel("Step")
plt.ylabel("Gini Coefficient")
plt.legend(title="Number of Agents (N)")
plt.grid(True)
plt.show()

# =========================
# Imports (Mesa 3.4.0)
# =========================
from mesa import Agent, Model
from mesa.time import RandomActivation
from mesa.space import MultiGrid
from mesa.datacollection import DataCollector

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

# =========================
# Gini coefficient
# =========================
def compute_gini(model):
    agent_wealths = [agent.wealth for agent in model.schedule.agents]  # Collect agent wealths
    x = sorted(agent_wealths)  # Sort wealth values
    N = model.num_agents
    total = sum(x)
    if N == 0 or total == 0:
        return 0.0
    B = sum((i + 1) * xi for i, xi in enumerate(x)) / (N * total)  # Gini formula component
    return 1 + (1 / N) - 2 * B  # Final Gini coefficient

# =========================
# Agent definition
# =========================
class MoneyAgent(Agent):
    """An agent with fixed initial wealth."""

    def __init__(self, unique_id, model):
        super().__init__(unique_id, model)
        self.wealth = 1

    def move(self):
        possible_steps = self.model.grid.get_neighborhood(
            self.pos, moore=True, include_center=False
        )
        new_position = self.random.choice(possible_steps)
        self.model.grid.move_agent(self, new_position)

    def give_money(self):
        cellmates = self.model.grid.get_cell_list_contents([self.pos])
        if len(cellmates) > 1 and self.wealth > 0:
            other = self.random.choice([a for a in cellmates if a is not self])
            other.wealth += 1
            self.wealth -= 1

    def step(self):
        self.move()
        self.give_money()

# =========================
# Model definition
# =========================
class MoneyModel(Model):
    """A model with some number of agents."""

    def __init__(self, N, width, height):
        super().__init__()
        self.num_agents = N
        self.grid = MultiGrid(width, height, torus=True)
        self.schedule = RandomActivation(self)

        # Create agents and place them on the grid
        for i in range(self.num_agents):
            a = MoneyAgent(i, self)  # unique_id=i, model=self
            self.schedule.add(a)
            x = self.random.randrange(self.grid.width)
            y = self.random.randrange(self.grid.height)
            self.grid.place_agent(a, (x, y))

        # Initialize a DataCollector
        self.datacollector = DataCollector(
            model_reporters={"Gini": compute_gini},  # Model-level data: Gini coefficient
            agent_reporters={"Wealth": "wealth"}     # Agent-level data: Wealth of each agent
        )

        # Collect data at step 0 (initial state of the model)
        self.datacollector.collect(self)

    def step(self):
        self.schedule.step()          # Randomly activate each agent
        self.datacollector.collect(self)  # Collect data after the step

# =========================
# Run model
# =========================
model = MoneyModel(10, 10, 10)
for _ in range(100):
    model.step()

# =========================
# Access collected data
# =========================
# Model-level dataframe (Gini over steps)
gini_df = model.datacollector.get_model_vars_dataframe()
print(gini_df.head())

# Agent-level dataframe (wealth per agent per step)
agent_wealth_df = model.datacollector.get_agent_vars_dataframe()
print(agent_wealth_df.tail())
print(agent_wealth_df.head())

# =========================
# Plot current wealth histogram (at final step)
# =========================
agent_wealth = [agent.wealth for agent in model.schedule.agents]
plt.hist(agent_wealth, bins=range(0, max(agent_wealth) + 2), edgecolor='black')
plt.xlabel("Wealth")
plt.ylabel("Number of Agents")
plt.title("Wealth Distribution After 100 Steps")
plt.show()

# =========================
# Compute and print final Gini
# =========================
final_gini = compute_gini(model)
print("Final Gini coefficient:", final_gini)

# =========================
# Plot Gini over time
# =========================
gini_df.plot(y="Gini", legend=False)
plt.xlabel("Step")
plt.ylabel("Gini Coefficient")
plt.title("Gini Coefficient Over Time")
plt.grid(True)
plt.show()

# =========================
# Heatmap of agents per cell (final state)
# =========================
agent_counts = np.zeros((model.grid.width, model.grid.height))
for cell_content, x, y in model.grid.coord_iter():
    agent_counts[x][y] = len(cell_content)

sns.heatmap(agent_counts, cmap="viridis", annot=True, cbar=False, square=True)
plt.title("Number of Agents per Cell (Final State)")
plt.show()

# =========================
# Imports
# =========================
from mesa import Agent, Model
from mesa.time import RandomActivation
from mesa.space import MultiGrid
from mesa.datacollection import DataCollector

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
import mesa

# =========================
# Gini coefficient
# =========================
def compute_gini(model):
    agent_wealths = [agent.wealth for agent in model.schedule.agents]
    x = sorted(agent_wealths)
    N = model.num_agents
    total = sum(x)
    if N == 0 or total == 0:
        return 0.0
    B = sum((i + 1) * xi for i, xi in enumerate(x)) / (N * total)
    return 1 + (1 / N) - 2 * B

# =========================
# Agent definition
# =========================
class MoneyAgent(Agent):
    def __init__(self, unique_id, model):
        super().__init__(unique_id, model)
        self.wealth = 1

    def move(self):
        possible_steps = self.model.grid.get_neighborhood(
            self.pos, moore=True, include_center=False
        )
        new_position = self.random.choice(possible_steps)
        self.model.grid.move_agent(self, new_position)

    def give_money(self):
        cellmates = self.model.grid.get_cell_list_contents([self.pos])
        if len(cellmates) > 1 and self.wealth > 0:
            other = self.random.choice([a for a in cellmates if a is not self])
            other.wealth += 1
            self.wealth -= 1

    def step(self):
        self.move()
        self.give_money()

# =========================
# Model definition
# =========================
class MoneyModel(Model):
    def __init__(self, N, width=10, height=10):
        super().__init__()
        self.num_agents = N
        self.grid = MultiGrid(width, height, torus=True)
        self.schedule = RandomActivation(self)

        # Create and place agents
        for i in range(self.num_agents):
            agent = MoneyAgent(i, self)
            self.schedule.add(agent)
            x = self.random.randrange(width)
            y = self.random.randrange(height)
            self.grid.place_agent(agent, (x, y))

        # ✅ Add DataCollector
        self.datacollector = DataCollector(
            model_reporters={"Gini": compute_gini},
            agent_reporters={"Wealth": "wealth"}
        )
        self.datacollector.collect(self)

    def step(self):
        self.schedule.step()
        self.datacollector.collect(self)

# =========================
# Batch runner
# =========================
params = {
    "N": np.arange(10, 51, 10),
    "width": 10,
    "height": 10
}

param_run = mesa.batch_run(
    MoneyModel,
    parameters=params,
    iterations=1,
    max_steps=30,
    number_processes=1,
    data_collection_period=1,
    display_progress=True
)

batch_ID_results = pd.DataFrame(param_run)

# =========================
# Plot results
# =========================
plt.figure(figsize=(12, 6))
sns.lineplot(data=batch_ID_results, x="Step", y="Gini", hue="N", marker="o")
plt.title("Gini Coefficient Over Time for Different Agent Counts (N)")
plt.xlabel("Step")
plt.ylabel("Gini Coefficient")
plt.legend(title="Number of Agents (N)")
plt.grid(True)
plt.show()
